trigger:
  branches:
    include:
      - main
      - release/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: Docker@2
  inputs:
    containerRegistry: 'robbalecontainerregistry'
    repository: 'sprint3-webapp-nextjs'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
  displayName: 'Build and push Docker image'
  