trigger:
  branches:
    include:
    - main
    - release/*
    - azure-pipelines-trial1

variables:
  azureSubscription: 'azuredevops_to_azurewebapps'
  webAppName: 'azure-webgl'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install dependencies and build'

- task: Docker@2
  inputs:
    containerRegistry: 'robbalecontainerregistry'
    repository: 'sprint3-webapp-nextjs'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)
  displayName: 'Build and push Docker image'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(webAppName)'
    containers: 'robbalecontainerregistry.azurecr.io/sprint3-webapp-nextjs:$(Build.BuildId)'
  displayName: 'Deploy to Azure Web App'
